.TH MATE-TERMINAL "1" "11 December 2014" "MATE Desktop Environment" "User Commands"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
mate-terminal \- manual page for MATE Terminal Emulator
.SH DESCRIPTION
.SS "Usage:"
.IP
mate\-terminal [OPTION...]
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-terminal\fR
Show terminal options
.TP
\fB\-\-help\-window\-options\fR
Show per\-window options
.TP
\fB\-\-help\-terminal\-options\fR
Show per\-terminal options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.TP
\fB\-\-help\-sm\-client\fR
Show session management options
.SS "Options to open new windows or terminal tabs; more than one of these may be specified:"
.TP
\fB\-\-window\fR
Open a new window containing a tab with the default profile
.TP
\fB\-\-tab\fR
Open a new tab in the last\-opened window with the default profile
.SS "Window options; if used before the first --window or --tab argument, sets the default for all windows:"
.TP
\fB\-\-show\-menubar\fR
Turn on the menubar
.TP
\fB\-\-hide\-menubar\fR
Turn off the menubar
.TP
\fB\-\-maximize\fR
Maximize the window
.TP
\fB\-\-full\-screen\fR
Full\-screen the window
.TP
\fB\-\-geometry\fR=\fIGEOMETRY\fR
Set the window size; for example: 80x24, or 80x24+200+200 (COLSxROWS+X+Y)
.TP
\fB\-\-role\fR=\fIROLE\fR
Set the window role
.TP
\fB\-\-active\fR
Set the last specified tab as the active one in its window
.SS "Terminal options; if used before the first --window or --tab argument, sets the default for all terminals:"
.TP
\fB\-e\fR, \fB\-\-command\fR
Execute the argument to this option inside the terminal
.TP
\fB\-x\fR, \fB\-\-execute\fR
Execute the remainder of the command line inside the terminal
.TP
\fB\-\-profile\fR=\fIPROFILE\-NAME\fR
Use the given profile instead of the default profile
.TP
\fB\-t\fR, \fB\-\-title\fR=\fITITLE\fR
Set the terminal title
.TP
\fB\-\-working\-directory\fR=\fIDIRNAME\fR
Set the working directory
.TP
\fB\-\-zoom\fR=\fIZOOM\fR
Set the terminal's zoom factor (1.0 = normal size)
.PP
GTK+ Options
.TP
\fB\-\-class\fR=\fICLASS\fR
Program class as used by the window manager
.TP
\fB\-\-name\fR=\fINAME\fR
Program name as used by the window manager
.TP
\fB\-\-screen\fR=\fISCREEN\fR
X screen to use
.TP
\fB\-\-sync\fR
Make X calls synchronous
.TP
\fB\-\-gtk\-module\fR=\fIMODULES\fR
Load additional GTK+ modules
.TP
\fB\-\-g\-fatal\-warnings\fR
Make all warnings fatal
.SS "Session management options:"
.TP
\fB\-\-sm\-client\-disable\fR
Disable connection to session manager
.TP
\fB\-\-sm\-client\-state\-file\fR=\fIFILE\fR
Specify file containing saved configuration
.TP
\fB\-\-sm\-client\-id\fR=\fIID\fR
Specify session management ID
.SS "Application Options:"
.TP
\fB\-\-disable\-factory\fR
Do not register with the activation nameserver, do not re\-use an active terminal
.TP
\fB\-\-load\-config\fR=\fIFILE\fR
Load a terminal configuration file
.TP
\fB\-\-save\-config\fR=\fIFILE\fR
Save the terminal configuration to a file
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.PP
.SH "Author"
Adam Erdman <hekel@archlinux.info> (2014) and Abel McClendon <hcmmac@hosscomm.com> (2014)
.P
for the
.B Mate Documentation Team.
.SH "See Also"
The full documentation for
.B mate-terminal
is maintained as a Texinfo manual.
.PP
If the
.B info
and
.B mate-terminal
programs are properly installed at your site, the command
.IP
.B info mate-terminal
.PP
should give you access to the complete manual.
.PP
More
.B MATE Terminal
documentation can be found from the
.B "Help"
menu, or by pressing the
.B F1
key.
.PP
Further information may also be available at:
.B http://wiki.mate-desktop.org/docs
